### ISSUE TITLE
Defaults to root directory

### ISSUE THREAD

**Issue by jaasum** [nqthqn/sancho#1]
I have this installed locally for the project and am running it via npm `npm run -- --sd module`. It works as expected but seems to only output on the root directory (I was in the modulerules directory). Not sure how it's deciding where to output, but it would make sense to always default to the current directory.

Update: does not happen with npx.

**Comment by nqthqn** [comment]
Correct — this is not meant to be run as an npm script. In a future release we could add a config so it knows where your modules live and could be run from anywhere. For now `npx` and maybe a bash alias should do the trick for local usage.
