### ISSUE TITLE
-n argument returns "undefined"

### ISSUE THREAD

**Issue by jaasum** [nqthqn/sancho#2]
I attempted to use -n by passing a module name that didn't exist yet and all I got back was `results is not defined`. I then entered a module name that does exist and I got back `results is not defined`.

**Comment by nqthqn** [comment]
This was a scope related bug.

**before**
```js
  try {
    let results = thesaurus.search(fromName).synonyms.join(', ');
  } catch(e) {
    shell.echo(chalk.red("Could not access thesaurus."));
    shell.exit(1);
  }
```

**after**
```js
  let results = null;
  try {
    results = thesaurus.search(fromName).synonyms.join(', ');
  } catch(e) {
    shell.echo(chalk.red("Could not access thesaurus."));
    shell.exit(1);
  }
```
There's probably a cleaner way of fixing this. Fixed in v0.0.3.
https://github.com/nqthqn/sancho/commit/54d148791fcc9d4ddaaed3aad7728837cf40b1bf
