### ISSUE TITLE
Feature Request: Ability to "label" a component

### ISSUE THREAD

**Issue by jaasum** [nqthqn/sancho#5]
When creating a component it would be nice to pass a string, a name (what currently happens) or both.

`sancho "Detail Card"` could translate to `_detailcard.scss`, `detailcard.hbs`, etc. with `label: 'Detail Card'` in the config.

Then if I want to create a layout I could pass both:

`sancho "Detail Card" -name l-detailcard` would create `_l-detailcard.scss`, `l-detailcard.hbs`, etc. still with `label: 'Detail Card'` in the config.

**Comment by nqthqn** [comment]
Right sancho only supports three arguments:

```js
const flag = process.argv[2];
const fromName = process.argv[3];
const toName = process.argv[4];
```

I suppose adding `l` to the scaffold command might work so

```sh
sancho -sdl modname "Module Name"
``` 

could also label the module. This would be consistent with

```sh
sancho -sd modname
``` 

In a future version we might add more flexibility with the flags.

**Comment by jaasum** [comment]
Ah, perhaps I tried to solve the problem instead of just stating it. Just being able to pass in a label is really the goal.

Sometimes the label would determine the name and save a step, but not always (as with layouts, you'd always want to pass two arguments).
